# docker-compose.yaml
version: '3.7'

services:
  #  rabbitmq:
  #    container_name: cv-base-rabbitmq
  #    image: rabbitmq:3.8.3-management
  #    restart: always
  #    environment:
  #      - RABBITMQ_DEFAULT_USER=admin
  #      - RABBITMQ_DEFAULT_PASS=admin
  #      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
  #    ports:
  #      - 15672:15672
  #      - 5672:5672
  #    volumes:
  #      - ./rabbitmq:/var/lib/rabbitmq
  postgres:
    image: postgres:latest
    container_name: footy-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - database_postgres:/var/lib/postgresql/data
volumes:
  database_postgres:
  minio-storage: